# Generated by Django 5.0.6 on 2024-06-24 08:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='uu_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
