# Generated by Django 5.0.6 on 2024-06-24 21:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='uu_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
