# Generated by Django 5.0.6 on 2024-06-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_uu_id_cart_uu_id1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='uu_id1',
        ),
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
