# Generated by Django 5.0.6 on 2024-06-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_products_colors_alter_products_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='colors',
            field=models.ManyToManyField(blank=True, default='black', to='app.color'),
        ),
    ]
